# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

COPY .env /app/.env

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.lock
RUN pip install --no-cache-dir -r requirements.lock

# Make port 80 available to the world outside this container
EXPOSE 80
EXPOSE 81

# Run app.py when the container launches
CMD ["python", "agent.py"]